### ISSUE TITLE
Incorrect single pixel diffs with SVG

### ISSUE THREAD

**Issue by JamesIves** [percy/percy-storybook#101]
I'm running into an issue with some of my components which purely return an SVG. It seems that Percy is picking up a single pixel diff pretty randomly. You can see the diff below, as there's no change in this story I'd expect it to be consistent, but for whatever reason it's showing one. I've experimented with this by accepting the changes, running the story through the test again, and seeing a change despite no code being checked in.

Old:
![image](https://user-images.githubusercontent.com/10888441/58704964-befd5400-837b-11e9-8428-9db9ecfcbe66.png)

New:
![image](https://user-images.githubusercontent.com/10888441/58704720-f91a2600-837a-11e9-829a-157b41e8d362.png)

Diff:
![image](https://user-images.githubusercontent.com/10888441/58704724-ffa89d80-837a-11e9-8329-b3ebc05d71b0.png)

Is there some sort of config setting I'm missing for this? The implementation is more or less right out of the box. From what I can tell this occurs even if the SVG is animated or not.

**Comment by Robdel12** [comment]
Hey James! Thanks for reporting this. Can you link to a build where this is happening (here or through intercom chat)? This should be an ignored diff

cc: @djones

**Comment by JamesIves** [comment]
`1960651` is the id in the url - This happens quite frequently with a number of svg diffs.

**Comment by JamesIves** [comment]
I've also attempted to skip this Story and the diffs still run on it;

```
stories.add(
  'default',
  () => (
    <ChanceOfSuccess
      {...defaultProps({
        percent: 50,
        draft: false,
        running: false,
        compact: false,
      })}
    />
  ),
  {percy: {skip: true}}
);
```

I've got Percy enabled globally in the Storybook config; do I need to do something else?

**Comment by timhaines** [comment]
@JamesIves Re the skipping not working, it looks like you're using percy-storybook v2 (an older version), with the v3 options.

You have two options here. If you're using Storybook v5, you can update to @percy/storybook v3 (note the package name has changed).  Or you can use the old deprecated way of skipping a story, using `addWithPercyOptions` detailed here: https://docs.percy.io/docs/storybook-for-react#section-per-story-options.

So, that will let you skip the story. If you want to keep it..

As to why the diff is occurring, I agree that is frustrating. We do [ignore isolated single pixel diffs](https://docs.percy.io/docs/ignoring-1px-diffs).  What you've pasted above appears to be a 2 pixel diff due to the SVG rendering non-deterministically.  

We've seen good results with setting the SVG's the shape-rendering to geometricPrecision.  `svg { shape-rendering: geometricPrecision; }`.  Could you try that please?  If that works, we can guide you through applying that CSS only in Percy's rendering environment, if that's suitable.

**Comment by timhaines** [comment]
@JamesIves Actually, I've just been reminded that we set `svg { shape-rendering: geometricPrecision; }` automatically now - so you doing it manually won't solve the issue.

**Comment by JamesIves** [comment]
Aha, I had no idea there was an updated package. I'll update the package and skip the story for now.

**Comment by Robdel12** [comment]
Going to close this out since it's an infrastructure issue and not an SDK issue. When these kinds of things comes up, you can use the snapshot feedback form:

<img width="1138" alt="feedback" src="https://user-images.githubusercontent.com/2072894/120011560-0dae4a80-bfa4-11eb-82e8-18bb764e8ae8.png">

The team gets alerted each time (in a slack channel) when something is submitted there. Really helpful for us to track rendering issues 👍🏼
