### ISSUE TITLE
Percy fails after adding Auth0

### ISSUE THREAD

**Issue by danjunger** [percy/percy-storybook#267]
I've added Auth0 to my app but none of my snapshots depend on it.  Percy now fails to render every snapshot with this error:

![percy-fail](https://user-images.githubusercontent.com/5027877/103571137-39a72300-4e7f-11eb-983e-f5ec402aade1.png)

My snapshots all work locally, when viewed by opening the index.html file in a browser of when serving the assets locally over http.

How does Percy render these snapshots?

**Comment by Robdel12** [comment]
Hey @danjunger! This will be an issue in our infrastructure for quite some time (when JavaScript is enabled). In the error stack trace you can see we're not rendering on HTTPS (and also not `localhost`): `http://render.percy.local/` 

The browser API [`auth0-spa-js`](https://github.com/auth0/auth0-spa-js/) is using ([`Crypto.subtle`](https://developer.mozilla.org/en-US/docs/Web/API/Crypto/subtle)) needs any of these to match: 

```
(https, *, *)
(wss, *, *)
(*, localhost, *)
(*, 127/8, *)
(*, ::1/128, *)
(file, *, —)
```

Since we're not rendering on either a secure origin (`https`) or `localhost`, it will throw that error. 

You could work around this by using one of our SDKs that captures a DOM snapshot of the stories (like [PercyScript](docs.percy.io/docs/percyscript)). This captures the DOM state on your local machine and then rerenders it in our browsers (with JS disabled). The Storybook SDK is the only SDK we have that has JS enabled by default and _does not_ capture a DOM snapshot. 

In the near future (Q2-ish) we're going to be revamping the Storybook SDK to capture DOM snapshots (building upon [Percy CLI](https://github.com/percy/cli/)). Once that work is done, this issue will also go away (since JS wouldn't be enabled in our infra, no cyrpto error)
