### ISSUE TITLE
`@percy-io/in-percy` detection not working with `percy/storybook@4.x`

### ISSUE THREAD

**Issue by patocallaghan** [percy/percy-storybook#348]
## The problem

We've got an app which uses Nextjs, Storybook and the percy-storybook SDK to take snapshots in Percy. In some of our stories we use the [`@percy-io/in-percy`](https://github.com/percy/in-percy) library to substitute args to stories depending on whether we are rendering in Percy or not. For example, we will render regular videos in our local and preview environments, but if we render within Percy we replace the video with single frame videos to reduce snapshot flakiness.

The detection code looks something like the following:

```js
import inPercy from '@percy-io/in-percy
// .. snip ..
const props = {
  video: inPercy() ? './videos/static.mp4' : './videos/original-video.mp4'
}
// .. snip ..
```

This worked fine in `@percy/storybook` 3.3.1 but migrating to 4.x `inPercy()` has stopped working for us. The original video _always_ shows, never the `static` video because the `inPercy()` check _always_ returns `false`.

### Reproduction repos
To try and illustrate the point I've created the following repo both with v3 and v4 versions of percy-storybook. I've created the `Default Button` story which simply shows a blue button, but when we render in Percy we change the background of the button to purple. We make this change by adding a specific class when rendering within Percy

``` js
DefaultButton.args = {
  size: "small",
  label: "My Button",
  classNames: inPercy() ? "storybook-button--percy" : "",
  type: "primary",
};
```

This works fine in v3 but not in v4. You should be able to take both of these branches and try them out yourself by simply running `yarn snapshot`.

#### Repos
* Snapshotting using `@percy/storybook` v3.3.1: [reproduction branch name `patoc/percy-storybook-3`](https://github.com/patocallaghan/next-storybook/compare/patoc/percy-storybook-3)
![image](https://user-images.githubusercontent.com/685034/126991148-93b047d7-4c1e-4f34-bf99-9c3cb109f4c0.png)
* Snapshotting using `@percy/storybook` v4: [reproduction branch name `master`](https://github.com/patocallaghan/next-storybook)
![image](https://user-images.githubusercontent.com/685034/126991536-99caf6a5-cccc-4a2a-8dc1-2c7e58005d68.png)

## Environment

- Node version: 14.15.0
- `@percy/cli` version: @percy/cli@1.0.0-beta.60
- Version of Percy SDK you’re using: @percy/storybook@4.0.0-beta.2

I understand that `@percy/storybook` v4 uses `@percy/cli` under the hood so that's why things are no longer working but curious if you have any suggestion on how to make `inPercy()` work? If not, are there any alternative approaches we can use to swap content out depending on whether we are rendering in Percy or not?

**Comment by Robdel12** [comment]
Hey @patocallaghan! By default in the new Storybook SDK we take DOM snapshots & disable JavaScript in Percy's infra: https://github.com/percy/percy-storybook#unexpected-diffs `inPercy` doesn't work because JS isn't executing and that package is entirely this: 

```js
module.exports = function() {
  var hasHostname = typeof window === 'object' && window.location && window.location.hostname;
  return hasHostname && /proxyme\.percy\.io|render\.percy\.local/.test(window.location.hostname);
}
```

You can reenable JS for the build (or specific snapshots) for `inPercy` to work again.

**Comment by patocallaghan** [comment]
Thanks @Robdel12 🤦‍♂️ Can't believe I missed that. I retried by adding that config and it worked 🙇‍♂️

**Comment by Robdel12** [comment]
Heh, no worries! There were LOTS of changes, so it's easy to miss. I think we're going to add this to our upgrading docs explicitly before un-beta'ing 😃

@wwilsman also mentioned you could likely use storyparams instead of `inPercy`/enabling JS (https://storybook.js.org/docs/react/writing-stories/args). The new Storybook SDK has _a lot_ more features where you can nicely enumerate states for Percy: https://github.com/percy/percy-storybook#storybook-parameters

**Comment by sean-adams** [comment]
Hi, reopening this issue as I'm running into the same issue with percy/storybook 4.2.0 + percy/cli 1.0.5

My sample story:
```tsx
export const InPercyTest: FC = () =>
  inPercy() ? <div>inPercy Works</div> : <div>inPercy doesnt work</div>;
```

renders "inPercy doesnt work"

I have `enableJavascript` set to `true` in a global Storybook parameter (in preview.js) and it appears to be working for other use cases in the stories, e.g. date mocking.

Looking at the comment above (https://github.com/percy/percy-storybook/issues/348#issuecomment-886810486) I added an additional story that simply displays the value of `window.location.hostname`, which apparently turns out to be `localhost` in my Percy run, so seems like it might be the source of the issue?

**Comment by Robdel12** [comment]
Hey @sean-adams! 

> I added an additional story that simply displays the value of window.location.hostname, which apparently turns out to be localhost in my Percy run, so seems like it might be the source of the issue?

Not exactly, that package is to check if you're currently running inside of Percy's rendering infrastructure. So locally the hostname will be localhost, but in Percy's browsers prior to screenshots it'll be a different hostname that's being checked. That package will only work on stories with JS enabled, since it requires JS to run inside of the browser at render time. 

The only way to really debug this would be to share a snapshot ID or build URL with a snapshot that's not behaving correctly 🤨

**Comment by sean-adams** [comment]
Hey @Robdel12 thanks for the response!

We do have JS enabled for all stories as we found we needed it for date mocking so that our relatively dated components didn't cause a diff on every Percy run.

I might not have been clear on the window.location piece - that was reporting `localhost` _in the Percy run_, in addition to in the local Storybook environment.

Here's the sample story I used:
```tsx
export const InPercyHostname: FC = () => (
  <div>
    {window.location?.hostname}
  </div>
);
```

Happy to share whatever I can to help, just let me know the best channel that avoids exposing anything sensitive in public :)
