### ISSUE TITLE
Unable to set different Storybook "config-dir"

### ISSUE THREAD

**Issue by WesSouza** [percy/percy-storybook#509]
My team uses the `-c` parameter when running Storybook:

```sh
start-storybook -c ./configs/storybook --ci --port 9001
```

The command `percy storybook:start` does not allow me to configure this, and therefore fails:

```
ERR! Error: No configuration files have been found in your configDir (/Users/wessouza/Sites/interface-percy/.storybook).
ERR! Storybook needs either a "main" or "config" file.
ERR!     at validateConfigurationFiles (/Users/wessouza/Sites/interface-percy/.yarn/unplugged/@storybook-core-virtual-3a1b859b16/node_modules/@storybook/core/dist/server/utils/validate-configuration-files.js:50:11)
```

It would be nice if this parameter was allowed, or there was a way of passing parameters through, such as:

```sh
percy storybook:start -- -c ./configs/storybook --ci --port 9001
```

**Comment by wwilsman** [comment]
The `-c` flag will not work because it is used by percy's own `--config` flag. The full Storybook flag for `--config-dir` should always work though.

Also, `-- -c ...` _should_ work, however we previously relied on oclif to parse flags, which might explain why it didn't. I'd give that syntax another shot with the latest version of this SDK. 

Also, if using yarn, it likes to strip `--` from commands. So you'll have to double up on it to get it to listen.
i.e. `yarn percy storybook:start -- -- -c ...`
